### ISSUE TITLE
Cant withdraw money

### ISSUE THREAD

**Issue by Arm-0001** [tabarra/txAdmin-recipes#2]
from discord (hey guys. i just got finished getting plume all up and running. im just having one issue. how do i use my money? i go to stores and cant buy bread or water. but theres money in the bank. dont see an atm anywhere so wondering how to get cash in pocket. been trying to find a guide or video. or maybe im missing something. anyhelp would be appreciated thank you.) bassically a atm script or something similar is needed to withdraw money

**Comment by RadhwaneDZ** [comment]
Stores take money from cash not bank , for atm try add new_banking script
